FROM python:3.10.2-alpine3.15


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# 
WORKDIR /code

RUN apk upgrade && \
    apk update


RUN apk add gdal proj geos
# 

COPY Pip* /code

# 
RUN pip install --no-cache-dir --upgrade  pipenv 


RUN pipenv install --system --deploy

# 
VOLUME [ "/code" ]


